### ISSUE TITLE
Setting SO_REUSEADDR option on inet socket not working

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#1083]
`Connect()` using socket with bound port to it causes `EADDRINUSE` error even though sock option `SO_REUSEADDR` is set.

Reproduction:
First run this script on `rpi` U1 from `ull` rack unit:
```python
import socket

ull_u1_addr = '192.168.72.21'
port = 2000
dest_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
dest_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
dest_socket.bind((ull_u1_addr, port))
dest_socket.listen(1000)
print('Listening...')
while True:
        con, _ = dest_socket.accept()
        print('Accepted')

```

Then run this hello program on `ull` U1, but remember to set ip address to 192.168.72.121 before.

```C
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdint.h>
#include <sys/wait.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>

#define DEST_ADDR "192.168.72.21"
#define SRC_ADDR "192.168.72.121"

int main(void)
{
	int sockfd;
	struct sockaddr_in dest_addr;
	struct sockaddr_in src_addr;
	uint16_t dest_port = 2000;
	uint16_t src_port = 2001;

	if ((sockfd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)) < 0) {
		perror("socket");
		close(sockfd);
		exit(EXIT_FAILURE);
	}

	int reuse = 1;
	if (setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof reuse) < 0) {
		perror("socksetopt");
		close(sockfd);
		exit(EXIT_FAILURE);
	}

	memset(&src_addr, 0, sizeof src_addr);
	src_addr.sin_family = AF_INET;
	src_addr.sin_addr.s_addr = inet_addr(SRC_ADDR);
	src_addr.sin_port = htons(src_port);

	if (bind(sockfd, (struct sockaddr *)&src_addr, sizeof src_addr) < 0) {
		perror("bind");
		close(sockfd);
		exit(EXIT_FAILURE);
	}

	memset(&dest_addr, 0, sizeof dest_addr);
	dest_addr.sin_family = AF_INET;
	dest_addr.sin_addr.s_addr = inet_addr(DEST_ADDR);
	dest_addr.sin_port = htons(dest_port);

	if (connect(sockfd, (struct sockaddr *)&dest_addr, sizeof dest_addr) < 0) {
		perror("connect");
		close(sockfd);
		exit(EXIT_FAILURE);
	}

	close(sockfd);

	return 0;
}
```
Current output:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/108683715/31fb2b70-1358-4588-a919-4827b6a555ee)

**Comment by nalajcie** [comment]
hmm, regarding (1) - see the compilation warnings:
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/3939983/0442bff5-7306-4a1a-be69-b8a9f05d0f95)

after fixing the code:
```c
dest_addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK)
// or 
#define DEST_ADDR "127.0.0.1"
```
it works as expected.

What happens - you bind yourself to some random address and the child keeps listening (the parent exits because `connect` fails) - check `ps` for existence of `hello` process. As some process keeps listening on this addr:port - another one fails to bind to it.


Regarding (2) - it's highly unusual to `bind` before `connect`, haven't checked that particular use case, so there might be some error there (usually we don't care about originating port in TCP, we use ephemeral one (assigned by the OS)).
