### ISSUE TITLE
busybox: crash after pipe yes command output to head -c 9999 (or other large value)

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#145]
![Screenshot from 2021-07-14 14-54-27](https://user-images.githubusercontent.com/77304431/125625423-9f794c8f-4282-4e8e-9f02-c8f8a1a25dbf.png)
![Screenshot from 2021-07-14 14-48-52](https://user-images.githubusercontent.com/77304431/125624680-79ecabe2-76a9-42f1-ae60-711c759d822e.png)

To reproduce:
1. edit /etc/rc.psh in rootskel like that (for posixsrv run in background):
![Screenshot from 2021-07-14 14-50-28](https://user-images.githubusercontent.com/77304431/125624923-53ac5301-00cc-4141-9bd7-c4c1bb9488d6.png)
2. run system image
3. run /bin/psh /etc/rc.psh (for posixsrv run in background)
4. run /bin/sh
5. run yes abc | head -c 9999

**Comment by damianloew** [comment]
That's occurs only when building for uart (not always)

**Comment by Maxez** [comment]
Short explanation on what was the issue:
`yes` gets blocked on write to pipe (pipe buffer is full) while `head` has already read all the bytes it wanted. `head` terminates and pipe_close() gets called but it doesn't wake up `yes` which stays blocked on write to pipe.

The issue didn't show up when using pc-tty because writing to pc-tty is apparently faster than writing to uart16550 and pipe buffer never got full.
