### ISSUE TITLE
armv7a9-zynq7000: problem with double to unsigned int assignment , when specific conditions are met

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#402]
When executing the following program:
![Screenshot from 2022-05-11 13-16-44](https://user-images.githubusercontent.com/77304431/167845516-94a8c067-6a4c-4dc2-b35d-8123e04f0214.png)
We've got the following output:
![Screenshot from 2022-05-11 13-17-05](https://user-images.githubusercontent.com/77304431/167845679-4c1f0888-4f06-4168-b818-211aafa421ca.png)
instead of printing `2` and then exit with 0 return code.

 - Exception undef is raised during floating point operations (the vfma.f64 instruction)
 - Cases, where the issue isn't raised:
   - casting to `float` instead of `double`
   - using some int number instead of rand()
   - removing `printf("%u\n", u)` from the code
   - casting double expression to `unsigned int`: `(unsigned int)(((double)ran / (double)2147483647) * 200000)`

**Comment by HBuczynski** [comment]
After short investigation, the calculations on the double precision numbers cause jump to `_exception_undef`. I would assume that some message should be printed but it doesn't.
The exception is caused by the instruction `vfma.f64`. I think that `FPU` should be checked, it was inherited from `imx6ull`.
