### ISSUE TITLE
Lacks in unsetenv function.

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#631]
According to Open Group unsetenv should return -1 and set errno to EINVAL when empty string is passed as argument.

```C
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>

int main(void){
        int ret;
        ret = unsetenv("");
        if (ret != 0) {
                fprintf(stderr, "unset with empty string name failed as it should: %s\n", strerror(errno));
                printf("ret: %d errno: %d\n", ret, errno);
        }
	else {
	        fprintf(stderr, "unset with empty string didn't fail but should\n");
                printf("ret: %d errno: %d\n", ret, errno);
	}

    return 0;
}
```

**Outcome on host-generic**:
![image](https://user-images.githubusercontent.com/108683715/224684791-2b1a7b1d-b111-401f-b845-46b15e837b52.png)

**Outcome on ia32-generic-qemu**:
![image](https://user-images.githubusercontent.com/108683715/224690671-6551b4c9-a9dc-406c-9e6a-5736bffc87ac.png)

**Comment by gerard5** [comment]
@adamdebek I see in the edit history that the problem was also with `setenv()`
> ... Passing NULL as second argument to setenv causes exception.

but issue description has been redacted, you mention in the issue title that also `setenv()` lacks functionality. If it's about the second argument -- this is `well known` undefined behavior -- of course I can fix it like in glibc (see [a thread here](https://patchwork.ozlabs.org/project/glibc/patch/CALoOobNSbWUkd_i-L6U0ovbqPYnJY-h=ftX1K61yb19pmJj6aw@mail.gmail.com/#986239), similar problem), but than we should extend the docs, because "The Open Group (tm)" describes second argument very general:
> ..  The environment variable shall be set to the value to which `envval` points. ..
and
> .. The strings described by `envname` and `envval` are copied by this function. ..

So I believe that's why the issue description was redacted.

**Comment by gerard5** [comment]
@adamdebek I've added fix for `unsetenv()` which will close the issue, please verify if it solves the issue, then I'll merge it if `setenv()` should be fixed in this pull-request as well please indicate it.

**Comment by adamdebek** [comment]
Yes, you are right i will change the title of this issue, the only problem is with unsetenv() and setenv() should remain as it is.
