### ISSUE TITLE
Lack of controlling terminal functionality

### ISSUE THREAD

**Issue by adamdebek** [phoenix-rtos/phoenix-rtos-project#808]
Controlling terminal is part of POSIX standard.

**Comment by nalajcie** [comment]
Please be more specific in regards to what is missing. AFAIK we do support all termios functionality (see `libtty` for details)

**Comment by adamdebek** [comment]
I meant all staff related to job control, controlling processes and terminal associated with session, but since it isn't required by POSIX I guess this issue has to be closed and phoenix.

**Comment by nalajcie** [comment]
That's why it's necessary to describe clearly what you meant ;).

AFAIK job control is part of POSIX shell specification, psh is not meant to be posix-compliant. We do support BusyBox ash which is posix-compliant. If I remember correctly the job control support is currently not compiled in (might indeed need some OS support which is missing right now). You may verify it yourself and follow up with more specific issue / feature request.
