### ISSUE TITLE
Are stripped binary `c++` files size are right?

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#903]
In the process of creating a simple `c++` test with only one include (iostream), I noticed that the test couldn't be loaded on `armv7m4-stm32l4x6-nucleo`, because the file was too large to fit in. 

After checking sizes and compare them with `GCC` build noticed huge difference:

 * Build by toolchain:
![Screenshot from 2023-10-26 08-34-24](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/49757239/7f0a8759-040c-4a0f-add1-3162fea96661)
 * Build by GCC:
![Screenshot from 2023-10-26 08-36-00](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/49757239/480e2a44-5548-44d8-84d2-9eb10e48f668)

I was thinking that strip wasn't working on `c++` binaries, but after checking with _stdio.h and printf_ instead _iostream and cout_ the output was like this:

 * Build by toolchain:
![Screenshot from 2023-10-26 08-43-16](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/49757239/6e3b2cea-d8b7-40b5-8a96-7ab84bd498a4)
 * Build by GCC:
![Screenshot from 2023-10-26 08-43-29](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/49757239/906da12a-9416-4c43-8b6d-305f7dad21ad)

Code to reproduction:
```c++
#include <iostream>
//#include <stdio.h>

int main(void)
{
	std::cout << "Hello World++!" << std::endl;
	// printf("Hello World++!");
	return 0;
}
```
My question is that `right behaviour`, or it is an `issue`?

**Comment by nalajcie** [comment]
Not sure what do you mean by writing "build by GCC", if you're compiling on host - ensure you're linking statically (seems like you're not). In my setup:
`g++ -O2 -static main.cpp  -o hello_host; strip hello_host`

results in a binary with **1.8 MB size** (note - this is also due to glibc instead of libphoenix)

The binary size is correct, using C++ standard library takes it's toll, also C++ support for exceptions and RTTI adds much to the binary size. Using `iostream` pulls all iostream support (with utf8, locale, strings, printifn different types, etc.), to display which functions are included in the unstripped binary (and sort them by size), you can use:
`nm --print-size --size-sort --radix=d -C hellocpp`

Inspecting this list shows that indeed functions mostly related to the functionalities mentioned above are linked into the binary (and they do have a considerable size):
![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/3939983/5e0726d1-5101-43bc-809b-4fdeda99b89e)
