### ISSUE TITLE
Some POSIX requirements

### ISSUE THREAD

**Issue by KArkadiusz** [phoenix-rtos/phoenix-rtos-project#915]
No OPEN_MAX (for directories) defined for any of targets.
No SYMLOOP_MAX defined for host_generic_pc.
No file permission system.

**Comment by mateusz-bloch** [comment]
If something is not working properly with host-generic-pc and it's not due to our configuration, I wouldn't report it because the fault lies directly with Ubuntu, not us.

It's also worth adding a reference or at least checking whether the latest version of POSIX defines what is missing.

And a last nitpick: If you know specifically what is not working, it would be good to describe it, as in the case of "No file permission system." I assume the issue relates to a lack of enforcement of permissions, which may not affect every target. So, it would also be helpful to note if something isn't working on a particular target or a specific filesystem.

**Comment by nalajcie** [comment]
Please note at the specific wording in the POSIX standard, especially:

_A definition of one of the symbolic constants in the following list shall be omitted from <limits.h> on specific implementations where the corresponding value is equal to or greater than the stated minimum, but is unspecified._

(as per https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/limits.h.html)

So it's conformant with POSIX to not specify these values if they're not compile-time consts.

You shouldn't assume these values would be consts in tests (but you can test if they are and use them then probably).

**Comment by KArkadiusz** [comment]
Okay, I'm closing the issue.

As mentioned, the first two constants aren't required by POSIX to be defined.

Third problem, with permissions, was that directory without any permission could still be opened from within the test, which made one of opendir() testcases useless. I was told that's how it should be, because on our system the only user is root, and with root privileges by default it is possible to open directories even without required permissions. In the tests it was possible to open directory without any permission, so I considered it was some kind of unwanted behaviour.
